import { useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import type { PlanProps } from './Planner';
import { format, ItemIcon, normalize } from './controls';

export function Recipes({ catalog, plan, setPlan }: PlanProps) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('');
  const [filter, setFilter] = useState('all');
  const enabled = new Set(plan.settings.enabledRecipeIds);
  const buildings = new Set(plan.settings.enabledBuildingIds);
  const items = new Map(catalog.items.map(i => [i.id, i]));
  const filtered = useMemo(() => catalog.recipes.filter(recipe => {
    const search = normalize([recipe.name, recipe.nameEn, ...[...recipe.inputs, ...recipe.outputs].flatMap(i => [items.get(i.itemId)?.name, items.get(i.itemId)?.nameEn])].join(' '));
    return search.includes(normalize(query)) && (!category || category === recipe.category) && (filter !== 'alternate' || recipe.alternate) && (filter !== 'enabled' || enabled.has(recipe.id)) && (filter !== 'available' || buildings.has(recipe.buildingId));
  }), [catalog, query, category, filter, plan.settings.enabledRecipeIds, plan.settings.enabledBuildingIds]);
  const toggle = (ids: string[], on: boolean) => { const next = new Set(enabled); ids.forEach(id => on ? next.add(id) : next.delete(id)); setPlan({ ...plan, settings: { ...plan.settings, enabledRecipeIds: [...next] } }); };
  return <div className="catalog-view"><div className="panel catalog-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Поиск рецептов" placeholder="Найти рецепт, продукт или ингредиент…" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Категория рецептов" value={category} onChange={e => setCategory(e.target.value)}><option value="">Все категории</option>{catalog.categories.map(c => <option key={c}>{c}</option>)}</select><select aria-label="Фильтр рецептов" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Все рецепты</option><option value="alternate">Альтернативные</option><option value="enabled">Включённые</option><option value="available">Доступные здания</option></select></div><div className="catalog-summary"><span>Найдено {filtered.length} · включено {enabled.size} из {catalog.recipes.length}</span><div><button className="text-button" onClick={() => toggle(filtered.map(r => r.id), true)}>Включить найденные</button><button className="text-button muted" onClick={() => toggle(filtered.map(r => r.id), false)}>Выключить</button></div></div><div className="recipe-grid">{filtered.map(recipe => <article className={`panel recipe-card ${enabled.has(recipe.id) ? 'enabled' : ''}`} key={recipe.id}><div className="recipe-title"><ItemIcon item={items.get(recipe.outputs[0]?.itemId ?? '')} size={42} /><div><h3>{recipe.name}</h3><small>{catalog.buildings.find(b => b.id === recipe.buildingId)?.name} · {format(recipe.seconds)} с</small></div><label className="switch"><input type="checkbox" aria-label={`Включить рецепт ${recipe.name}`} checked={enabled.has(recipe.id)} onChange={e => toggle([recipe.id], e.target.checked)} /><span /></label></div><div className="recipe-tags"><span>{recipe.category}</span>{recipe.alternate && <span className="alt">Альтернативный</span>}{!buildings.has(recipe.buildingId) && <span className="unavailable">Здание отключено</span>}</div><div className="recipe-equation"><div><small>ВХОД ЗА ЦИКЛ</small>{recipe.inputs.map(i => <span key={i.itemId}><ItemIcon item={items.get(i.itemId)} size={22} />{format(i.amount)} × {items.get(i.itemId)?.name}</span>)}</div><div><small>ВЫХОД ЗА ЦИКЛ</small>{recipe.outputs.map(i => <span key={i.itemId}><ItemIcon item={items.get(i.itemId)} size={22} />{format(i.amount)} × {items.get(i.itemId)?.name}</span>)}</div></div></article>)}</div>{!filtered.length && <div className="panel empty-panel"><Search size={32} /><h3>Ничего не найдено</h3><p>Попробуйте другое название или снимите фильтры.</p></div>}</div>;
}
