import { chooseMaximum } from './chooseVariant';
import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { createDefaultPlan } from '../../packages/domain/defaults';
import { createFactory, createWorld, emptyWorkspace } from '../../packages/domain/worlds';
import type { Catalog } from '../../packages/domain/types';
const catalog = JSON.parse(readFileSync(new URL('../../packages/game-data/catalog.json', import.meta.url), 'utf8')) as Catalog;
test.use({ baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:5173' });

test('партия: запас, срок, готовые позиции и сохранение', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Режим партии', { exact: true }).check();
  await page.getByLabel('Желаемое время партии, минут').fill('30');
  await page.getByLabel(/^Требуется:/).fill('100');
  await page.getByLabel(/^На складе:/).fill('40');
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  await chooseMaximum(page);
  await expect(page.locator('.results-heading').getByText('Допустимое приближение', { exact: true })).toBeVisible({ timeout: 30000 });
  await expect(page.locator('.batch-result')).toContainText('30');
  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('button', { name: 'Цели и ограничения', exact: true }).click();
  await page.getByLabel(/^На складе:/).fill('100');
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  await chooseMaximum(page);
  await expect(page.locator('.batch-result')).toContainText('готов', { timeout: 30000 });
  await page.reload();
  await expect(page.getByLabel(/^На складе:/)).toHaveValue('100');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
  await page.locator('.batch-panel').screenshot({ path: 'output/playwright/p2-batch-mobile.png' });
});

test('усилитель, существующая линия, сравнение и строительная ведомость', async ({ page }) => {
  const plan = createDefaultPlan(catalog); plan.settings.objective = 'smooth-power';
  plan.targets = [{ itemId: 'iron-rod', rate: 1, weight: 1, scale: 1 }];
  plan.sources = [{ id: 'ingot', name: 'Со склада фабрики', itemId: 'iron-ingot', kind: 'flow', limit: 15, count: 1, purity: 1, minerId: '', clock: 100, importPower: 2 }];
  plan.settings.enabledRecipeIds = ['iron-rod'];
  plan.lines = [{ id: 'old', name: 'Старый конструктор', recipeId: 'iron-rod', count: 1, clock: 100, duty: 1, somersloops: 1, locked: true }]; plan.expansion = 'keep'; plan.somersloopBudget = 1;
  await page.addInitScript(p => localStorage.setItem('ficsit-plan-v1', JSON.stringify(p)), plan);
  await page.goto('/');
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  await chooseMaximum(page);
  await expect(page.locator('.results-heading').getByText('Оптимум найден', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: 'Построить', exact: true }).click();
  await expect(page.locator('.construction-panel')).toContainText('Старый конструктор');
  await expect(page.locator('.construction-panel')).toContainText('Новых машин: 0');
  await expect(page.locator('.construction-panel')).toContainText('Somersloops на машину: 1');
  await expect(page.locator('.utilization')).toContainText('энергия учтена');
  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('button', { name: 'Цели и ограничения', exact: true }).click();
  await page.getByText('Проверки расширения и перестройки', { exact: true }).click();
  await page.getByRole('button', { name: 'Сравнить оставить / добавить / перестроить' }).click();
  await expect(page.getByRole('heading', { name: 'Результаты сравнения', exact: true })).toBeVisible({ timeout: 30000 });
  await expect(page.locator('.analysis-panel')).toContainText('Перестроить');
  await page.getByText('Расширение фабрики и усилители', { exact: true }).click();
  await page.getByLabel('Бюджет Somersloops', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  await chooseMaximum(page);
  await expect(page.getByRole('heading', { name: 'Заказ невыполним', exact: true })).toBeVisible({ timeout: 30000 });
});

test('скважина, заметки, резерв и мощность сохраняются', async ({ page }) => {
  const plan = createDefaultPlan(catalog); plan.settings.objective = 'smooth-power'; plan.targets = [{ itemId: 'water', rate: 1, weight: 1, scale: 1 }];
  await page.addInitScript(p => localStorage.setItem('ficsit-plan-v1', JSON.stringify(p)), plan);
  await page.goto('/');
  await page.getByLabel('Тип источника 1', { exact: true }).selectOption('well');
  await page.getByLabel('Спутников скважины 1.1', { exact: true }).fill('2');
  await page.getByText('Заметка, резерв и энергия импорта', { exact: true }).first().click();
  await page.getByLabel('Заметка источника 1', { exact: true }).fill('Южная скважина');
  await page.getByLabel('Резерв источника 1', { exact: true }).fill('20');
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  await chooseMaximum(page);
  await expect(page.locator('.results-heading').getByText('Допустимое приближение', { exact: true })).toBeVisible({ timeout: 30000 });
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-plan-v1')!));
  expect(saved.sources[0]).toMatchObject({ kind: 'well', notes: 'Южная скважина', reserve: 20, well: { satellites: [{ purity: 1, count: 2 }] } });
  await expect(page.locator('.results-column')).toContainText('150');
  await expect(page.locator('.utilization')).toContainText('Скважина');
});

test('квоты двух фабрик не могут превысить общий узел при сохранении', async ({ page }) => {
  const plan = createDefaultPlan(catalog); plan.settings.objective = 'smooth-power'; plan.name = 'Первая';
  const world = { ...createWorld(catalog, 'Общий мир', 'shared', plan), resourceNodes: [{ id: 'iron-node', name: 'Северный узел', itemId: 'iron-ore', limit: 120 }] };
  plan.sources = [{ id: 'quota', itemId: 'iron-ore', kind: 'flow', limit: 70, count: 1, purity: 1, minerId: '', clock: 100, sharedNodeId: 'iron-node' }];
  const first = createFactory(plan, 'first', world);
  const second = createFactory({ ...plan, name: 'Вторая', sources: [{ ...plan.sources[0], limit: 40 }] }, 'second', world);
  const workspace = { ...emptyWorkspace(catalog.version), worlds: [world], factories: [first, second] };
  await page.addInitScript(w => localStorage.setItem('ficsit-workspace-v1', JSON.stringify(w)), workspace);
  await page.goto('/');
  await page.getByRole('button', { name: 'Миры и фабрики', exact: true }).click();
  await page.getByRole('button', { name: 'Открыть Первая', exact: true }).click();
  await page.getByRole('button', { name: 'Цели и ограничения', exact: true }).click();
  await page.getByLabel('Квота общего узла quota', { exact: true }).fill('90');
  await page.getByRole('button', { name: 'Миры и фабрики', exact: true }).click();
  await page.getByRole('button', { name: 'Сохранить фабрику «Первая»', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('превышает');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-workspace-v1')!).factories[0].plan.sources[0].limit)).toBe(70);
  await page.getByRole('button', { name: 'Цели и ограничения', exact: true }).click();
  await page.getByLabel('Квота общего узла quota', { exact: true }).fill('80');
  await page.getByRole('button', { name: 'Миры и фабрики', exact: true }).click();
  await page.getByRole('button', { name: 'Сохранить фабрику «Первая»', exact: true }).click();
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-workspace-v1')!).factories[0].plan.sources[0].limit)).toBe(80);
  await page.getByRole('button', { name: 'Цели и ограничения', exact: true }).click();
  await page.getByLabel('Тип источника 1', { exact: true }).selectOption('well');
  await page.getByLabel('Общий узел источника quota', { exact: true }).selectOption('iron-node');
  await page.getByLabel('Квота общего узла quota', { exact: true }).fill('80');
  await page.getByRole('button', { name: 'Миры и фабрики', exact: true }).click();
  await page.getByRole('button', { name: 'Сохранить фабрику «Первая»', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-workspace-v1')!).factories[0].plan.sources[0].well)).toBeUndefined();
});
