import { expect, test, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import type { Catalog, Plan } from '../../packages/domain/types';
import { createDefaultPlan } from '../../packages/domain/defaults';
import { createWorld, createFactory, emptyWorkspace } from '../../packages/domain/worlds';
const catalog = JSON.parse(readFileSync('packages/game-data/catalog.json', 'utf8')) as Catalog;
test.use({ baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:5173' });
const draft = (page: Page): Promise<Plan> => page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-plan-v1')!));
async function open(page: Page) {
  await page.goto('/'); await page.getByRole('button', { name: 'Рецепты', exact: true }).click();
  await page.getByText('Быстрая настройка по прогрессу', { exact: true }).click();
}
test('настройка: замена, добавление, независимый MAM и перезагрузка', async ({ page }) => {
  await open(page);
  await page.getByLabel('Всё до уровня HUB').selectOption('0');
  await page.getByRole('button', { name: 'Выбрать всё до уровня 0', exact: true }).click();
  await page.getByLabel('Альтернативы в настройке').selectOption('none');
  const initial = await draft(page);
  await page.getByRole('button', { name: 'Заменить набор', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Просмотр настройки рецептов' })).toContainText('Выключить');
  await expect(page.getByRole('region', { name: 'Просмотр настройки рецептов' })).toBeFocused();
  await page.locator('.recipe-setup').screenshot({ path: 'output/playwright/recipe-setup-desktop.png' });
  expect((await draft(page)).settings.enabledRecipeIds).toEqual(initial.settings.enabledRecipeIds);
  await page.getByRole('button', { name: 'Применить настройку', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Заменить набор', exact: true })).toBeFocused();
  await expect.poll(async () => (await draft(page)).settings.enabledRecipeIds.includes('plastic')).toBe(false);
  expect((await draft(page)).settings.enabledRecipeIds).toContain('iron-plate');
  await page.getByRole('button', { name: 'Исследования MAM', exact: true }).click();
  await page.locator('.recipe-setup summary').filter({ hasText: /^Кварц$/ }).click();
  const research = catalog.unlocks!.find(u => u.id === 'Research_Quartz_2_C')!;
  await page.getByLabel(`Исследование: ${research.name}`, { exact: true }).check();
  await page.getByRole('button', { name: 'Добавить к текущему', exact: true }).click();
  await page.getByRole('button', { name: 'Применить настройку', exact: true }).click();
  await expect.poll(async () => (await draft(page)).settings.enabledRecipeIds.includes('crystal-oscillator')).toBe(true);
  expect((await draft(page)).settings.enabledRecipeIds).toContain('iron-plate');
  await page.reload(); await page.getByRole('button', { name: 'Рецепты', exact: true }).click();
  await page.getByText('Быстрая настройка по прогрессу', { exact: true }).click();
  await page.getByRole('button', { name: 'Исследования MAM', exact: true }).click();
  await page.locator('.recipe-setup summary').filter({ hasText: /^Кварц$/ }).click();
  await expect(page.getByLabel(`Исследование: ${research.name}`, { exact: true })).toBeChecked();
});
test('совместимые фильтры дисков и MAM, сортировка ранних рецептов, мобильная ширина', async ({ page }) => {
  await open(page);
  await expect(page.getByLabel('Сортировка рецептов')).toHaveValue('progress');
  const first = await page.locator('.recipe-card').first().getByRole('heading').textContent();
  expect(first).toBeTruthy();
  await page.getByLabel('Источник открытия рецептов').selectOption('hard-drive');
  await page.getByLabel('Фильтр рецептов', { exact: true }).selectOption('disabled');
  await expect(page.locator('.recipe-card').first()).toBeVisible();
  const names = await page.locator('.recipe-card h3').allTextContents();
  expect(names).not.toContain('Турботопливо');
  await page.getByLabel('Источник открытия рецептов').selectOption('mam');
  await page.getByLabel('Фильтр рецептов', { exact: true }).selectOption('all');
  await page.getByLabel('Направление MAM').selectOption('BPD_ResearchTree_Quartz_C');
  await expect(page.locator('.recipe-card').filter({ has: page.getByRole('heading', { name: 'Кремнезём', exact: true }) })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.locator('.recipe-setup').screenshot({ path: 'output/playwright/recipe-setup-mobile.png' });
});
test('клавиатурный выбор уровня, частичная группа, отмена и отдельное добавление дисков', async ({ page }) => {
  await open(page);
  const setup = page.locator('.recipe-setup');
  const phase = catalog.gamePhases!.find(p => 0 <= p.lastTier)!;
  await setup.locator('summary').filter({ hasText: phase.name }).click();
  await setup.locator('summary').filter({ hasText: /^Уровень HUB 0$/ }).click();
  const group = page.getByRole('checkbox', { name: /Весь уровень HUB 0/ });
  await group.focus(); await page.keyboard.press('Space');
  await expect(group).toBeChecked();
  const child = setup.getByRole('checkbox', { name: 'Этап: ' + catalog.unlocks!.find(u => u.id === 'Schematic_Tutorial2_C')!.name, exact: true });
  await child.uncheck();
  await expect(group).toHaveJSProperty('indeterminate', true);
  const before = await draft(page);
  await page.getByRole('button', { name: 'Заменить набор', exact: true }).click();
  await page.getByRole('button', { name: 'Отменить просмотр', exact: true }).click();
  expect(await draft(page)).toEqual(before);
  await page.getByRole('button', { name: 'Добавить все подходящие альтернативы', exact: true }).click();
  await page.getByRole('button', { name: 'Применить настройку', exact: true }).click();
  await expect.poll(async () => (await draft(page)).settings.enabledRecipeIds.includes('alt-screw')).toBe(true);
  expect((await draft(page)).settings.enabledBuildingIds).toEqual(before.settings.enabledBuildingIds);
  expect((await draft(page)).settings.enabledRecipeIds).toEqual(expect.arrayContaining(before.settings.enabledRecipeIds));
});
test('общий мир: просмотр фабрик, атомарное применение, сохранение чужих запретов', async ({ page }) => {
  const world = createWorld(catalog, 'Общий', 'shared-progress');
  const plan = createDefaultPlan(catalog);
  const a = createFactory(plan, 'a', world), b = createFactory(plan, 'b', world);
  b.plan.settings.enabledRecipeIds = [];
  const workspace = { ...emptyWorkspace(catalog.version), worlds: [world], factories: [a, b] };
  await page.addInitScript(value => localStorage.setItem('ficsit-workspace-v1', JSON.stringify(value)), workspace);
  await page.goto('/'); await page.getByRole('button', { name: 'Миры и фабрики', exact: true }).click();
  await page.getByRole('button', { name: `Открыть ${a.name}`, exact: true }).first().click();
  await page.getByRole('button', { name: 'Рецепты', exact: true }).click();
  await page.getByText('Быстрая настройка по прогрессу', { exact: true }).click();
  await page.getByRole('button', { name: 'Выбрать всё до уровня 0', exact: true }).click();
  await page.getByRole('button', { name: 'Заменить набор', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Просмотр настройки рецептов' })).toContainText('Связанных фабрик: 2');
  await page.getByRole('button', { name: 'Применить настройку', exact: true }).click();
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-workspace-v1')!).worlds[0].revision)).toBe(2);
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-workspace-v1')!));
  expect(saved.factories[1].plan.settings.enabledRecipeIds).toEqual([]);
  expect(saved.factories[0].plan.settings.enabledRecipeIds).toContain('iron-plate');
});
