import { expect, test } from '@playwright/test';

test.use({ baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:5173' });

test('стандартная фабрика с глубиной 4 даёт два варианта и реальные ленты в обоих видах', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/');
  await page.getByRole('checkbox', { name: 'Учитывать схемы разделителей и соединителей', exact: true }).check();
  await page.getByRole('combobox', { name: 'Максимальная глубина', exact: true }).selectOption('4');
  const started = Date.now();
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  const maximum = page.getByRole('article', { name: 'Максимальный выпуск', exact: true });
  const economy = page.getByRole('article', { name: 'Экономия энергии', exact: true });
  await expect(maximum.getByRole('button', { name: 'Использовать вариант', exact: true })).toBeEnabled({ timeout: 35_000 });
  await expect(economy.getByRole('button', { name: 'Использовать вариант', exact: true })).toBeEnabled();
  await expect(maximum.locator('.variant-metrics > div').first()).toContainText('10 шт/мин');
  await expect(economy.locator('.variant-metrics > div').first()).toContainText('9 шт/мин');
  const calculationMs = Date.now() - started;
  await maximum.getByRole('button', { name: 'Использовать вариант', exact: true }).click();
  await expect(page.locator('.results-heading .status-badge')).toHaveText('Допустимое приближение');
  await page.getByRole('button', { name: 'Построить', exact: true }).click();
  await page.getByRole('button', { name: 'По типам зданий', exact: true }).click();
  const graph = page.getByRole('region', { name: 'Схема строительства', exact: true });
  await expect(graph.locator('.schematic-node.junction').first()).toBeVisible();
  await expect(graph).not.toContainText('УСЛОВНЫЙ БЛОК');
  const groupedRates = await graph.locator('.schematic-edges g.flow').evaluateAll(nodes => nodes.map(node => [node.getAttribute('data-item-id'), Number(node.getAttribute('data-rate'))]));
  const devices = await graph.locator('.schematic-node.junction').count();
  expect(devices).toBeGreaterThan(0);
  await graph.getByRole('button', { name: 'Уместить', exact: true }).click();
  await graph.screenshot({ path: 'output/playwright/default-routing-types.png' });
  await page.getByRole('button', { name: 'По отдельным зданиям', exact: true }).click();
  await expect(graph.locator('.schematic-node.junction')).toHaveCount(devices);
  expect(await graph.locator('.schematic-edges g.flow').evaluateAll(nodes => nodes.map(node => [node.getAttribute('data-item-id'), Number(node.getAttribute('data-rate'))]))).toEqual(groupedRates);
  await expect(graph).toContainText('Все физические конвейерные связи показаны');
  await graph.getByRole('button', { name: 'Уместить', exact: true }).click();
  await graph.screenshot({ path: 'output/playwright/default-routing-machines.png' });
  await page.getByRole('button', { name: 'Вернуться к вариантам', exact: true }).click();
  await economy.getByRole('button', { name: 'Использовать вариант', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Скопировать: Выпуск: Усиленная железная пластина', exact: true })).toHaveText('9 шт/мин');
  await page.getByRole('button', { name: 'Построить', exact: true }).click();
  await page.getByRole('button', { name: 'По отдельным зданиям', exact: true }).click();
  await expect(graph.locator('.schematic-node.junction').first()).toBeVisible();
  await expect(graph).not.toContainText('УСЛОВНЫЙ БЛОК');
  expect(errors).toEqual([]);
  await testInfo.attach('routing-default-smoke', { body: JSON.stringify({ calculationMs, maximum: 10, economy: 9, devices, physicalEdges: groupedRates.length, errors }), contentType: 'application/json' });
});

test('выключение учёта на стандартной фабрике сохраняет глубину и возвращает обычную схему', async ({ page }) => {
  await page.goto('/');
  const enabled = page.getByRole('checkbox', { name: 'Учитывать схемы разделителей и соединителей', exact: true });
  const depth = page.getByRole('combobox', { name: 'Максимальная глубина', exact: true });
  await enabled.check();
  await depth.selectOption('4');
  await enabled.uncheck();
  await expect(depth).toBeDisabled();
  await expect(depth).toHaveValue('4');
  await page.reload();
  await expect(enabled).not.toBeChecked();
  await expect(depth).toHaveValue('4');
  await expect(depth).toBeDisabled();
  await page.getByRole('button', { name: 'Рассчитать', exact: true }).click();
  const maximum = page.getByRole('article', { name: 'Максимальный выпуск', exact: true });
  await expect(maximum.getByRole('button', { name: 'Использовать вариант', exact: true })).toBeEnabled({ timeout: 30_000 });
  await maximum.getByRole('button', { name: 'Использовать вариант', exact: true }).click();
  await expect(page.locator('.results-heading .status-badge')).toHaveText('Допустимое приближение');
  await page.getByRole('button', { name: 'Построить', exact: true }).click();
  await page.getByRole('button', { name: 'По отдельным зданиям', exact: true }).click();
  const graph = page.getByRole('region', { name: 'Схема строительства', exact: true });
  await expect(graph.locator('.schematic-node[data-kind="building"]')).toHaveCount(15);
  await expect(graph.locator('.schematic-node.junction')).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('ficsit-plan-v1')!).settings.beltRouting)).toEqual({ enabled: false, maxDepth: 4 });
});
